"""YoDb V0.1 catalog loading, inspection contracts, and static validation."""

from .catalog import Catalog, CatalogValidationError, load_catalog
from .connections import (
    ConnectionReferenceResolver,
    ConnectionAdapterRegistry,
    MappingPostgresConnectionResolver,
    PostgresConnectionAdapter,
    PostgresConnectionReferenceResolver,
    PostgresConnectionSettings,
    SourceConnectionAdapter,
)
from .errors import (
    CatalogRuntimeError,
    ErrorCode,
    ErrorDetail,
    SourceConnectionError,
    SourceInspectionError,
    YoDbError,
)
from .inspection import (
    FindingSeverity,
    InspectionCapability,
    InspectionRequest,
    GraphRelationshipType,
    PhysicalCheckConstraint,
    PhysicalField,
    PhysicalForeignKey,
    PhysicalIndex,
    PhysicalKey,
    PhysicalResource,
    PhysicalUniqueConstraint,
    PostgresCatalogValidator,
    PostgresSourceInspector,
    ResourceKind,
    InspectionAdapterBinding,
    SourceCatalogValidator,
    SourceInspection,
    SourceInspectionRegistry,
    SourceInspector,
    SourceValidationReport,
    ValidationFinding,
)
from .runtime import (
    CatalogEvaluation,
    CatalogRefreshResult,
    InMemoryCatalogRuntime,
    RefreshStatus,
    SourceRuntimeState,
    SourceRuntimeStatus,
)

__all__ = [
    "Catalog",
    "CatalogEvaluation",
    "CatalogRefreshResult",
    "CatalogRuntimeError",
    "CatalogValidationError",
    "ConnectionReferenceResolver",
    "ConnectionAdapterRegistry",
    "ErrorCode",
    "ErrorDetail",
    "FindingSeverity",
    "GraphRelationshipType",
    "InspectionCapability",
    "InspectionAdapterBinding",
    "InspectionRequest",
    "MappingPostgresConnectionResolver",
    "InMemoryCatalogRuntime",
    "PhysicalField",
    "PhysicalCheckConstraint",
    "PhysicalForeignKey",
    "PhysicalIndex",
    "PhysicalKey",
    "PhysicalResource",
    "PhysicalUniqueConstraint",
    "PostgresCatalogValidator",
    "PostgresConnectionAdapter",
    "PostgresConnectionReferenceResolver",
    "PostgresConnectionSettings",
    "PostgresSourceInspector",
    "ResourceKind",
    "RefreshStatus",
    "SourceCatalogValidator",
    "SourceConnectionAdapter",
    "SourceConnectionError",
    "SourceInspectionError",
    "SourceInspection",
    "SourceInspectionRegistry",
    "SourceInspector",
    "SourceValidationReport",
    "SourceRuntimeState",
    "SourceRuntimeStatus",
    "ValidationFinding",
    "YoDbError",
    "load_catalog",
]
